
name: Test and Build

on:
  push:
    branches:
    - main
    paths:
    - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Setting up environment
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Setup
      uses: docker/setup-buildx-action@v2

    - name: Docker Credentials
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker tag
      id: version
      run: |
        VERSION=v$(date +"%Y%m%d%H%M%S")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ksajida/devops-assn:${{ env.VERSION }} .

    # Push the Docker Image
    - name: Push Docker Image
      run: |
        docker push ksajida/devops-assn:${{ env.VERSION }}

    # UPdate the K8s Manifest Files
    - name: Update K8s Manifests
      run: |
        cat deploy/deployment.yaml
        sed -i "s|image: ksajida/devops-assn:.*|image: ksajida/devops-assn:${{ env.VERSION }}|g" deploy/deployment.yaml
        cat deploy/deployment.yaml

    # Update Github
    - name: Commit the changes
      run: |
        git config --global user.name "Sajida Khanam"
        git config --global user.email "sajida@example.com"

        git add .
        
        # Commit only if there are changes
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Update Kubernetes manifest with new image version"
          git push
        fi


